// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class AspNetUserRoles
    {
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        [Required]
        public string RoleId { get; set; }

        [ForeignKey(nameof(UserId))]
        public virtual AspNetUsers User { get; set; }
    }
}