// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            TbExpensesPayment = new HashSet<TbExpensesPayment>();
            TbOrdersPatient = new HashSet<TbOrders>();
            TbOrdersUser = new HashSet<TbOrders>();
            TbPurchaseInvoices = new HashSet<TbPurchaseInvoices>();
            TbPurchasesReturns = new HashSet<TbPurchasesReturns>();
            TbSalesInvoices = new HashSet<TbSalesInvoices>();
            TbSalesReturns = new HashSet<TbSalesReturns>();
            TbStockTransactions = new HashSet<TbStockTransactions>();
            TbStockWithdrawAndDeposit = new HashSet<TbStockWithdrawAndDeposit>();
            TbStoresTransaction = new HashSet<TbStoresTransaction>();
        }

        [Key]
        public string Id { get; set; }
        [Required]
        [StringLength(200)]
        public string FullName { get; set; }
        [Required]
        [StringLength(200)]
        public string Pass { get; set; }
        public string Address { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [StringLength(256)]
        public string NormalizedUserName { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        [StringLength(256)]
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public int Code { get; set; }
        [Required]
        public string Gender { get; set; }
        public int Age { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<TbExpensesPayment> TbExpensesPayment { get; set; }
        [InverseProperty(nameof(TbOrders.Patient))]
        public virtual ICollection<TbOrders> TbOrdersPatient { get; set; }
        [InverseProperty(nameof(TbOrders.User))]
        public virtual ICollection<TbOrders> TbOrdersUser { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TbPurchaseInvoices> TbPurchaseInvoices { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TbPurchasesReturns> TbPurchasesReturns { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TbSalesInvoices> TbSalesInvoices { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TbSalesReturns> TbSalesReturns { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TbStockTransactions> TbStockTransactions { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TbStockWithdrawAndDeposit> TbStockWithdrawAndDeposit { get; set; }
        [InverseProperty("user")]
        public virtual ICollection<TbStoresTransaction> TbStoresTransaction { get; set; }
    }
}