// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SaidalyTechMain.Consts;

namespace SaidalyTechMain.DB_Models
{
    public partial class PharmacySystemContext : DbContext
    {
        public PharmacySystemContext()
        {
        }

        public PharmacySystemContext(DbContextOptions<PharmacySystemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TbAuthorization> TbAuthorization { get; set; }
        public virtual DbSet<TbCategories> TbCategories { get; set; }
        public virtual DbSet<TbCompanyInformation> TbCompanyInformation { get; set; }
        public virtual DbSet<TbCustomers> TbCustomers { get; set; }
        public virtual DbSet<TbDelivryMen> TbDelivryMen { get; set; }
        public virtual DbSet<TbExpenses> TbExpenses { get; set; }
        public virtual DbSet<TbExpensesPayment> TbExpensesPayment { get; set; }
        public virtual DbSet<TbForms> TbForms { get; set; }
        public virtual DbSet<TbGroups> TbGroups { get; set; }
        public virtual DbSet<TbItemProperties> TbItemProperties { get; set; }
        public virtual DbSet<TbItemUnits> TbItemUnits { get; set; }
        public virtual DbSet<TbItems> TbItems { get; set; }
        public virtual DbSet<TbOrders> TbOrders { get; set; }
        public virtual DbSet<TbOrdersItems> TbOrdersItems { get; set; }
        public virtual DbSet<TbPrinterSettings> TbPrinterSettings { get; set; }
        public virtual DbSet<TbPurchaseInvoiceItems> TbPurchaseInvoiceItems { get; set; }
        public virtual DbSet<TbPurchaseInvoices> TbPurchaseInvoices { get; set; }
        public virtual DbSet<TbPurchaseReturnsDitails> TbPurchaseReturnsDitails { get; set; }
        public virtual DbSet<TbPurchasesReturns> TbPurchasesReturns { get; set; }
        public virtual DbSet<TbSafes> TbSafes { get; set; }
        public virtual DbSet<TbSalesInvoiceItems> TbSalesInvoiceItems { get; set; }
        public virtual DbSet<TbSalesInvoices> TbSalesInvoices { get; set; }
        public virtual DbSet<TbSalesReturns> TbSalesReturns { get; set; }
        public virtual DbSet<TbSalesReturnsDitails> TbSalesReturnsDitails { get; set; }
        public virtual DbSet<TbShifts> TbShifts { get; set; }
        public virtual DbSet<TbStockTransactions> TbStockTransactions { get; set; }
        public virtual DbSet<TbStockWithdrawAndDeposit> TbStockWithdrawAndDeposit { get; set; }
        public virtual DbSet<TbStoreTransactionDetails> TbStoreTransactionDetails { get; set; }
        public virtual DbSet<TbStores> TbStores { get; set; }
        public virtual DbSet<TbStoresTransaction> TbStoresTransaction { get; set; }
        public virtual DbSet<TbSuppliers> TbSuppliers { get; set; }
        public virtual DbSet<TbTransaction> TbTransaction { get; set; }
        public virtual DbSet<TbTransactionTypes> TbTransactionTypes { get; set; }
        public virtual DbSet<TbUnits> TbUnits { get; set; }
        public virtual DbSet<VwAuthorizationWithFormName> VwAuthorizationWithFormName { get; set; }
        public virtual DbSet<VwAuthorizationWithNames> VwAuthorizationWithNames { get; set; }
        public virtual DbSet<VwCustomerLaterInShift> VwCustomerLaterInShift { get; set; }
        public virtual DbSet<VwCustomersAccountStatement> VwCustomersAccountStatement { get; set; }
        public virtual DbSet<VwCustomersBalance> VwCustomersBalance { get; set; }
        public virtual DbSet<VwCustomersTransactions> VwCustomersTransactions { get; set; }
        public virtual DbSet<VwDesktopUsers> VwDesktopUsers { get; set; }
        public virtual DbSet<VwEachStoreInventory> VwEachStoreInventory { get; set; }
        public virtual DbSet<VwExpensesReport> VwExpensesReport { get; set; }
        public virtual DbSet<VwFormsData> VwFormsData { get; set; }
        public virtual DbSet<VwItemsWithUnits> VwItemsWithUnits { get; set; }
        public virtual DbSet<VwOrderHead> VwOrderHead { get; set; }
        public virtual DbSet<VwOrderItem> VwOrderItem { get; set; }
        public virtual DbSet<VwPurchaseInvoiceHeds> VwPurchaseInvoiceHeds { get; set; }
        public virtual DbSet<VwPurchaseInvoiceitems> VwPurchaseInvoiceitems { get; set; }
        public virtual DbSet<VwPurchaseReturnsDetails> VwPurchaseReturnsDetails { get; set; }
        public virtual DbSet<VwPurchasesReturnsHeads> VwPurchasesReturnsHeads { get; set; }
        public virtual DbSet<VwRoles> VwRoles { get; set; }
        public virtual DbSet<VwRoshetaBody> VwRoshetaBody { get; set; }
        public virtual DbSet<VwRoshetaHead> VwRoshetaHead { get; set; }
        public virtual DbSet<VwRoshetaOrders> VwRoshetaOrders { get; set; }
        public virtual DbSet<VwRoshetaOrdersItems> VwRoshetaOrdersItems { get; set; }
        public virtual DbSet<VwSafesBalance> VwSafesBalance { get; set; }
        public virtual DbSet<VwSafesMoves> VwSafesMoves { get; set; }
        public virtual DbSet<VwSalesInvoiceHeds> VwSalesInvoiceHeds { get; set; }
        public virtual DbSet<VwSalesInvoiceItems> VwSalesInvoiceItems { get; set; }
        public virtual DbSet<VwSalesReturnsDetails> VwSalesReturnsDetails { get; set; }
        public virtual DbSet<VwSalesReturnsHeads> VwSalesReturnsHeads { get; set; }
        public virtual DbSet<VwStockTransactionsReport> VwStockTransactionsReport { get; set; }
        public virtual DbSet<VwStockWithdrawAndDeposit> VwStockWithdrawAndDeposit { get; set; }
        public virtual DbSet<VwStoreInventory> VwStoreInventory { get; set; }
        public virtual DbSet<VwStoresTransactionHeads> VwStoresTransactionHeads { get; set; }
        public virtual DbSet<VwSupplierInvoices> VwSupplierInvoices { get; set; }
        public virtual DbSet<VwSuppliersBalance> VwSuppliersBalance { get; set; }
        public virtual DbSet<VwSuppliersTransactions> VwSuppliersTransactions { get; set; }
        public virtual DbSet<VwSupplierssAccountStatement> VwSupplierssAccountStatement { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(AppConsts.ConnectionString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AspNetRoles>(entity =>
            {
                entity.HasIndex(e => e.NormalizedName)
                    .HasName("RoleNameIndex")
                    .IsUnique()
                    .HasFilter("([NormalizedName] IS NOT NULL)");
            });

            modelBuilder.Entity<AspNetUserRoles>(entity =>
            {
                entity.HasNoKey();

                entity.HasIndex(e => e.RoleId);
            });

            modelBuilder.Entity<AspNetUsers>(entity =>
            {
                entity.HasIndex(e => e.NormalizedEmail)
                    .HasName("EmailIndex");

                entity.HasIndex(e => e.NormalizedUserName)
                    .HasName("UserNameIndex")
                    .IsUnique()
                    .HasFilter("([NormalizedUserName] IS NOT NULL)");

                entity.Property(e => e.Gender).HasDefaultValueSql("(N'Male')");
            });

            modelBuilder.Entity<TbAuthorization>(entity =>
            {
                entity.HasOne(d => d.Form)
                    .WithMany(p => p.TbAuthorization)
                    .HasForeignKey(d => d.FormId)
                    .HasConstraintName("FK_TbAuthorization_TbForms");

                entity.HasOne(d => d.Jop)
                    .WithMany(p => p.TbAuthorization)
                    .HasForeignKey(d => d.JopId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TbAuthorization_AspNetRoles");
            });

            modelBuilder.Entity<TbCustomers>(entity =>
            {
                entity.Property(e => e.CreditLimit).HasDefaultValueSql("((0))");

                entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");
            });

            modelBuilder.Entity<TbExpenses>(entity =>
            {
                entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");
            });

            modelBuilder.Entity<TbExpensesPayment>(entity =>
            {
                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbExpensesPayment)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbExpensesPayment_AspNetUsers");
            });

            modelBuilder.Entity<TbForms>(entity =>
            {
                entity.Property(e => e.Authorized).HasDefaultValueSql("((0))");
            });

            modelBuilder.Entity<TbGroups>(entity =>
            {
                entity.HasOne(d => d.Item)
                    .WithMany(p => p.TbGroups)
                    .HasForeignKey(d => d.ItemId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_TbGroups_TbItems");
            });

            modelBuilder.Entity<TbItemProperties>(entity =>
            {
                entity.HasOne(d => d.Group)
                    .WithMany(p => p.TbItemProperties)
                    .HasForeignKey(d => d.GroupId)
                    .HasConstraintName("FK_TbProperties_TbGroups");
            });

            modelBuilder.Entity<TbItemUnits>(entity =>
            {
                entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

                entity.Property(e => e.PuchasePrice).HasDefaultValueSql("((0))");

                entity.Property(e => e.SalesPrice).HasDefaultValueSql("((1))");

                entity.Property(e => e.UnitsNumber).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Item)
                    .WithMany(p => p.TbItemUnits)
                    .HasForeignKey(d => d.ItemId)
                    .HasConstraintName("FK_TbProductUnits_TbProducts");

                entity.HasOne(d => d.Unit)
                    .WithMany(p => p.TbItemUnits)
                    .HasForeignKey(d => d.UnitId)
                    .HasConstraintName("FK_TbProductUnits_TbUnits");
            });

            modelBuilder.Entity<TbItems>(entity =>
            {
                entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

                entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.TbItems)
                    .HasForeignKey(d => d.CategoryId)
                    .HasConstraintName("FK_TbProducts_TbCategories");
            });

            modelBuilder.Entity<TbOrders>(entity =>
            {
                entity.Property(e => e.BloodPressure).HasDefaultValueSql("('0/0')");

                entity.Property(e => e.Diagnosis).HasDefaultValueSql("(' ')");

                entity.Property(e => e.Notes).HasDefaultValueSql("(' ')");

                entity.Property(e => e.OrderType).HasDefaultValueSql("('2')");

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.TbOrders)
                    .HasForeignKey(d => d.CustomerId)
                    .HasConstraintName("FK_TbOrders_TbCustomers");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.TbOrdersPatient)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK_TbOrders_AspNetUsers1");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbOrdersUser)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbOrders_AspNetUsers");
            });

            modelBuilder.Entity<TbOrdersItems>(entity =>
            {
                entity.Property(e => e.Notes).HasDefaultValueSql("(' ')");

                entity.Property(e => e.Price).HasDefaultValueSql("((0))");

                entity.Property(e => e.Qty).HasDefaultValueSql("((0))");

                entity.Property(e => e.Total).HasComputedColumnSql("([Price]*[Qty])");

                entity.HasOne(d => d.ItemUnit)
                    .WithMany(p => p.TbOrdersItems)
                    .HasForeignKey(d => d.ItemUnitId)
                    .HasConstraintName("FK_TbRoshetaItems_TbItemUnits");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.TbOrdersItems)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_TbRoshetaItems_TbRosheta");
            });

            modelBuilder.Entity<TbPrinterSettings>(entity =>
            {
                entity.HasOne(d => d.Category)
                    .WithMany(p => p.TbPrinterSettings)
                    .HasForeignKey(d => d.CategoryId)
                    .HasConstraintName("FK_TbPrinterSettings_TbCategories");
            });

            modelBuilder.Entity<TbPurchaseInvoiceItems>(entity =>
            {
                entity.Property(e => e.Discount).HasDefaultValueSql("((0))");

                entity.Property(e => e.Total).HasComputedColumnSql("([Qty]*[PurchasePrice]-[Discount])");

                entity.HasOne(d => d.Invoice)
                    .WithMany(p => p.TbPurchaseInvoiceItems)
                    .HasForeignKey(d => d.InvoiceId)
                    .HasConstraintName("FK_TbPurchaseInvoiceItems_TbPurchaseInvoices");

                entity.HasOne(d => d.ItemUnit)
                    .WithMany(p => p.TbPurchaseInvoiceItems)
                    .HasForeignKey(d => d.ItemUnitId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TbPurchaseInvoiceItems_TbItemUnits");
            });

            modelBuilder.Entity<TbPurchaseInvoices>(entity =>
            {
                entity.Property(e => e.Discount).HasDefaultValueSql("((0))");

                entity.Property(e => e.Later).HasComputedColumnSql("([Total]-[Cash])");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbPurchaseInvoices)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TbPurchaseInvoices_AspNetUsers");
            });

            modelBuilder.Entity<TbPurchaseReturnsDitails>(entity =>
            {
                entity.Property(e => e.Total).HasComputedColumnSql("([Qty]*[SalesPrice])");

                entity.HasOne(d => d.ItemUnit)
                    .WithMany(p => p.TbPurchaseReturnsDitails)
                    .HasForeignKey(d => d.ItemUnitId)
                    .HasConstraintName("FK_TbPurchaseReturnsDitails_TbItemUnits");

                entity.HasOne(d => d.Return)
                    .WithMany(p => p.TbPurchaseReturnsDitails)
                    .HasForeignKey(d => d.ReturnId)
                    .HasConstraintName("FK_TbPurchaseReturnsDitails_TbPurchasesReturns");
            });

            modelBuilder.Entity<TbPurchasesReturns>(entity =>
            {
                entity.Property(e => e.Discount).HasDefaultValueSql("((0))");

                entity.Property(e => e.StoreId).HasDefaultValueSql("((1))");

                entity.Property(e => e.Total).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Inv)
                    .WithMany(p => p.TbPurchasesReturns)
                    .HasForeignKey(d => d.InvId)
                    .HasConstraintName("FK_TbPurchasesReturns_TbPurchaseInvoices");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbPurchasesReturns)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbPurchasesReturns_AspNetUsers");
            });

            modelBuilder.Entity<TbSafes>(entity =>
            {
                entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");
            });

            modelBuilder.Entity<TbSalesInvoiceItems>(entity =>
            {
                entity.Property(e => e.Discount).HasDefaultValueSql("((0))");

                entity.Property(e => e.Total).HasComputedColumnSql("([Qty]*[SalesPrice]-[Discount])");

                entity.HasOne(d => d.Invoice)
                    .WithMany(p => p.TbSalesInvoiceItems)
                    .HasForeignKey(d => d.InvoiceId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_TbSalesInvoiceItems_TbSalesInvoices");

                entity.HasOne(d => d.ItemUnit)
                    .WithMany(p => p.TbSalesInvoiceItems)
                    .HasForeignKey(d => d.ItemUnitId)
                    .HasConstraintName("FK_TbSalesInvoiceItems_TbItemUnits");
            });

            modelBuilder.Entity<TbSalesInvoices>(entity =>
            {
                entity.Property(e => e.Cash).HasDefaultValueSql("((0))");

                entity.Property(e => e.Discount).HasDefaultValueSql("((0))");

                entity.Property(e => e.Later).HasComputedColumnSql("([Total]-([Cash]+[Discount]))");

                entity.Property(e => e.StoreId).HasDefaultValueSql("((1))");

                entity.Property(e => e.Total).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbSalesInvoices)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbSalesInvoices_AspNetUsers");
            });

            modelBuilder.Entity<TbSalesReturns>(entity =>
            {
                entity.Property(e => e.Discount).HasDefaultValueSql("((0))");

                entity.Property(e => e.InvType).HasDefaultValueSql("((1))");

                entity.Property(e => e.StoreId).HasDefaultValueSql("((1))");

                entity.Property(e => e.Total).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Inv)
                    .WithMany(p => p.TbSalesReturns)
                    .HasForeignKey(d => d.InvId)
                    .HasConstraintName("FK_TbSalesReturns_TbSalesInvoices");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbSalesReturns)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbSalesReturns_AspNetUsers");
            });

            modelBuilder.Entity<TbSalesReturnsDitails>(entity =>
            {
                entity.Property(e => e.Total).HasComputedColumnSql("([Qty]*[SalesPrice])");

                entity.HasOne(d => d.ItemUnit)
                    .WithMany(p => p.TbSalesReturnsDitails)
                    .HasForeignKey(d => d.ItemUnitId)
                    .HasConstraintName("FK_TbSalesReturnsDitails_TbItemUnits");

                entity.HasOne(d => d.Return)
                    .WithMany(p => p.TbSalesReturnsDitails)
                    .HasForeignKey(d => d.ReturnId)
                    .HasConstraintName("FK_TbSalesReturnsDitails_TbSalesReturns");
            });

            modelBuilder.Entity<TbShifts>(entity =>
            {
                entity.Property(e => e.OpeningBalance).HasDefaultValueSql("((0))");

                entity.Property(e => e.SafeBalance).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Safe)
                    .WithMany(p => p.TbShifts)
                    .HasForeignKey(d => d.SafeId)
                    .HasConstraintName("FK_TbShifts_TbSafes");
            });

            modelBuilder.Entity<TbStockTransactions>(entity =>
            {
                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbStockTransactions)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbStockTransactions_AspNetUsers");
            });

            modelBuilder.Entity<TbStockWithdrawAndDeposit>(entity =>
            {
                entity.HasOne(d => d.User)
                    .WithMany(p => p.TbStockWithdrawAndDeposit)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_TbStockWithdrawAndDeposit_AspNetUsers");
            });

            modelBuilder.Entity<TbStoreTransactionDetails>(entity =>
            {
                entity.HasOne(d => d.ItemUnit)
                    .WithMany(p => p.TbStoreTransactionDetails)
                    .HasForeignKey(d => d.ItemUnitId)
                    .HasConstraintName("FK_TbStoreTransactionDetails_TbItemUnits");

                entity.HasOne(d => d.Transaction)
                    .WithMany(p => p.TbStoreTransactionDetails)
                    .HasForeignKey(d => d.TransactionId)
                    .HasConstraintName("FK_TbStoreTransactionDetails_TbStoresTransaction");
            });

            modelBuilder.Entity<TbStoresTransaction>(entity =>
            {
                entity.HasOne(d => d.user)
                    .WithMany(p => p.TbStoresTransaction)
                    .HasForeignKey(d => d.userId)
                    .HasConstraintName("FK_TbStoresTransaction_AspNetUsers");
            });

            modelBuilder.Entity<TbTransaction>(entity =>
            {
                entity.Property(e => e.SheftId).HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Cust)
                    .WithMany(p => p.TbTransaction)
                    .HasForeignKey(d => d.CustId)
                    .HasConstraintName("FK_TbTransaction_TbCustomers");
            });

            modelBuilder.Entity<VwAuthorizationWithFormName>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwAuthorizationWithFormName");
            });

            modelBuilder.Entity<VwAuthorizationWithNames>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwAuthorizationWithNames");
            });

            modelBuilder.Entity<VwCustomerLaterInShift>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwCustomerLaterInShift");
            });

            modelBuilder.Entity<VwCustomersAccountStatement>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwCustomersAccountStatement");
            });

            modelBuilder.Entity<VwCustomersBalance>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwCustomersBalance");
            });

            modelBuilder.Entity<VwCustomersTransactions>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwCustomersTransactions");
            });

            modelBuilder.Entity<VwDesktopUsers>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwDesktopUsers");
            });

            modelBuilder.Entity<VwEachStoreInventory>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwEachStoreInventory");
            });

            modelBuilder.Entity<VwExpensesReport>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwExpensesReport");
            });

            modelBuilder.Entity<VwFormsData>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwFormsData");

                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<VwItemsWithUnits>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwItemsWithUnits");
            });

            modelBuilder.Entity<VwOrderHead>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwOrderHead");
            });

            modelBuilder.Entity<VwOrderItem>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwOrderItem");
            });

            modelBuilder.Entity<VwPurchaseInvoiceHeds>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwPurchaseInvoiceHeds");
            });

            modelBuilder.Entity<VwPurchaseInvoiceitems>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwPurchaseInvoiceitems");
            });

            modelBuilder.Entity<VwPurchaseReturnsDetails>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwPurchaseReturnsDetails");
            });

            modelBuilder.Entity<VwPurchasesReturnsHeads>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwPurchasesReturnsHeads");
            });

            modelBuilder.Entity<VwRoles>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwRoles");
            });

            modelBuilder.Entity<VwRoshetaBody>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwRoshetaBody");
            });

            modelBuilder.Entity<VwRoshetaHead>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwRoshetaHead");
            });

            modelBuilder.Entity<VwRoshetaOrders>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwRoshetaOrders");
            });

            modelBuilder.Entity<VwRoshetaOrdersItems>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwRoshetaOrdersItems");
            });

            modelBuilder.Entity<VwSafesBalance>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSafesBalance");
            });

            modelBuilder.Entity<VwSafesMoves>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSafesMoves");

                entity.Property(e => e.Type).IsUnicode(false);
            });

            modelBuilder.Entity<VwSalesInvoiceHeds>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSalesInvoiceHeds");
            });

            modelBuilder.Entity<VwSalesInvoiceItems>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSalesInvoiceItems");
            });

            modelBuilder.Entity<VwSalesReturnsDetails>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSalesReturnsDetails");
            });

            modelBuilder.Entity<VwSalesReturnsHeads>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSalesReturnsHeads");
            });

            modelBuilder.Entity<VwStockTransactionsReport>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwStockTransactionsReport");
            });

            modelBuilder.Entity<VwStockWithdrawAndDeposit>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwStockWithdrawAndDeposit");
            });

            modelBuilder.Entity<VwStoreInventory>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwStoreInventory");

                entity.Property(e => e.StoreName).IsUnicode(false);
            });

            modelBuilder.Entity<VwStoresTransactionHeads>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwStoresTransactionHeads");
            });

            modelBuilder.Entity<VwSupplierInvoices>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSupplierInvoices");
            });

            modelBuilder.Entity<VwSuppliersBalance>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSuppliersBalance");
            });

            modelBuilder.Entity<VwSuppliersTransactions>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSuppliersTransactions");
            });

            modelBuilder.Entity<VwSupplierssAccountStatement>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VwSupplierssAccountStatement");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}