// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbExpensesPayment
    {
        [Key]
        public int Id { get; set; }
        public int? ExpenseId { get; set; }
        public int? SafeId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Payment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public string Note { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? SheftId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(AspNetUsers.TbExpensesPayment))]
        public virtual AspNetUsers User { get; set; }
    }
}