// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbGroups
    {
        public TbGroups()
        {
            TbItemProperties = new HashSet<TbItemProperties>();
        }

        [Key]
        public int Id { get; set; }
        public int? ItemId { get; set; }

        [ForeignKey(nameof(ItemId))]
        [InverseProperty(nameof(TbItems.TbGroups))]
        public virtual TbItems Item { get; set; }
        [InverseProperty("Group")]
        public virtual ICollection<TbItemProperties> TbItemProperties { get; set; }
    }
}