// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbItems
    {
        public TbItems()
        {
            TbGroups = new HashSet<TbGroups>();
            TbItemUnits = new HashSet<TbItemUnits>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string ActiveIngredient { get; set; }
        public string Company { get; set; }
        public string Pamphlet { get; set; }
        public string Dosage { get; set; }
        public string Composition { get; set; }
        public int CategoryId { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public string ImageName { get; set; }
        public bool? IsDeleted { get; set; }
        public string Brief { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(TbCategories.TbItems))]
        public virtual TbCategories Category { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<TbGroups> TbGroups { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<TbItemUnits> TbItemUnits { get; set; }
    }
}