// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbOrders
    {
        public TbOrders()
        {
            TbOrdersItems = new HashSet<TbOrdersItems>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(450)]
        public string PatientId { get; set; }
        [StringLength(50)]
        public string BloodPressure { get; set; }
        public int Diabites { get; set; }
        public int BodyTempreature { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NextVisit { get; set; }
        public string Diagnosis { get; set; }
        public string Notes { get; set; }
        [StringLength(50)]
        public string OrderType { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty(nameof(TbCustomers.TbOrders))]
        public virtual TbCustomers Customer { get; set; }
        [ForeignKey(nameof(PatientId))]
        [InverseProperty(nameof(AspNetUsers.TbOrdersPatient))]
        public virtual AspNetUsers Patient { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(AspNetUsers.TbOrdersUser))]
        public virtual AspNetUsers User { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<TbOrdersItems> TbOrdersItems { get; set; }
    }
}