// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbPurchaseInvoiceItems
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        public int ItemUnitId { get; set; }
        public int InvoiceId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PurchasePrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(38, 4)")]
        public decimal? Total { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpiryDate { get; set; }

        [ForeignKey(nameof(InvoiceId))]
        [InverseProperty(nameof(TbPurchaseInvoices.TbPurchaseInvoiceItems))]
        public virtual TbPurchaseInvoices Invoice { get; set; }
        [ForeignKey(nameof(ItemUnitId))]
        [InverseProperty(nameof(TbItemUnits.TbPurchaseInvoiceItems))]
        public virtual TbItemUnits ItemUnit { get; set; }
    }
}