// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbSafes
    {
        public TbSafes()
        {
            TbShifts = new HashSet<TbShifts>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        public bool? IsActive { get; set; }

        [InverseProperty("Safe")]
        public virtual ICollection<TbShifts> TbShifts { get; set; }
    }
}