// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbSalesReturnsDitails
    {
        [Key]
        public int Id { get; set; }
        public int? ReturnId { get; set; }
        public int? ItemUnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SalesPrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "decimal(37, 4)")]
        public decimal? Total { get; set; }

        [ForeignKey(nameof(ItemUnitId))]
        [InverseProperty(nameof(TbItemUnits.TbSalesReturnsDitails))]
        public virtual TbItemUnits ItemUnit { get; set; }
        [ForeignKey(nameof(ReturnId))]
        [InverseProperty(nameof(TbSalesReturns.TbSalesReturnsDitails))]
        public virtual TbSalesReturns Return { get; set; }
    }
}