// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbShifts
    {
        [Key]
        public int Id { get; set; }
        [StringLength(450)]
        public string OpenUserId { get; set; }
        [StringLength(450)]
        public string CloseUserId { get; set; }
        [StringLength(200)]
        public string DeviceName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OpenDateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CloseDateTime { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? OpeningBalance { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? SafeBalance { get; set; }
        public int? SafeId { get; set; }

        [ForeignKey(nameof(SafeId))]
        [InverseProperty(nameof(TbSafes.TbShifts))]
        public virtual TbSafes Safe { get; set; }
    }
}