// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbStockTransactions
    {
        [Key]
        public int Id { get; set; }
        public int? SafeFromId { get; set; }
        public int? SafeToId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public string Note { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(AspNetUsers.TbStockTransactions))]
        public virtual AspNetUsers User { get; set; }
    }
}