// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbStoresTransaction
    {
        public TbStoresTransaction()
        {
            TbStoreTransactionDetails = new HashSet<TbStoreTransactionDetails>();
        }

        [Key]
        public int Id { get; set; }
        public int? IdStoreFrom { get; set; }
        public int? IdStoreTo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(450)]
        public string userId { get; set; }
        [StringLength(250)]
        public string Note { get; set; }

        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(AspNetUsers.TbStoresTransaction))]
        public virtual AspNetUsers user { get; set; }
        [InverseProperty("Transaction")]
        public virtual ICollection<TbStoreTransactionDetails> TbStoreTransactionDetails { get; set; }
    }
}