// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class TbTransaction
    {
        [Key]
        public int Id { get; set; }
        public int? CustId { get; set; }
        public int? SupplierId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Qty { get; set; }
        public bool? IsIncomming { get; set; }
        public int? SafeId { get; set; }
        public int? TransactionTypeId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(500)]
        public string note { get; set; }
        public int? SheftId { get; set; }

        [ForeignKey(nameof(CustId))]
        [InverseProperty(nameof(TbCustomers.TbTransaction))]
        public virtual TbCustomers Cust { get; set; }
    }
}