// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwCustomerLaterInShift
    {
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? later { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        public int? SheftId { get; set; }
        public int? SafeId { get; set; }
    }
}