// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwDesktopUsers
    {
        [Required]
        [StringLength(450)]
        public string Id { get; set; }
        [Required]
        [StringLength(200)]
        public string FullName { get; set; }
        [Required]
        [StringLength(200)]
        public string Pass { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        [StringLength(256)]
        public string RoleName { get; set; }
        [Required]
        [StringLength(450)]
        public string RoleId { get; set; }
    }
}