// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwPurchaseInvoiceitems
    {
        public int InvoiceId { get; set; }
        public string ItemArName { get; set; }
        [Required]
        [StringLength(200)]
        public string unitName { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PurchasePrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        public int UnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(38, 4)")]
        public decimal? Total { get; set; }
        public int RowId { get; set; }
        public int CategoryId { get; set; }
        public int ItemUnitId { get; set; }
        [StringLength(200)]
        public string Barcode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpiryDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
    }
}