// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwPurchaseReturnsDetails
    {
        public string name { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "decimal(37, 4)")]
        public decimal? Total { get; set; }
        public int? ReturnId { get; set; }
        public int? InvId { get; set; }
        public int? ItemUnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SalesPrice { get; set; }
        public int? StoreId { get; set; }
    }
}