// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwRoshetaHead
    {
        public int RoshetaId { get; set; }
        [StringLength(50)]
        public string OrderType { get; set; }
        [Required]
        [StringLength(450)]
        public string PatientId { get; set; }
        public int PatientCode { get; set; }
        public string DoctorAddress { get; set; }
        public string PatientAddress { get; set; }
        public int PatientAge { get; set; }
        [Required]
        public string PatientGender { get; set; }
        public string PatientPhoneNumber { get; set; }
        [Required]
        [StringLength(200)]
        public string PatientName { get; set; }
        [Required]
        [StringLength(450)]
        public string DoctorId { get; set; }
        [Required]
        [StringLength(200)]
        public string DoctorName { get; set; }
        public string DoctorPhoneNumber { get; set; }
        public string Diagnosis { get; set; }
        [StringLength(50)]
        public string BloodPressure { get; set; }
        public int Diabites { get; set; }
        public int BodyTempreature { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NextVisit { get; set; }
        public string Notes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
    }
}