// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwRoshetaOrdersItems
    {
        public int Id { get; set; }
        public int? ItemUnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        public int? OrderId { get; set; }
        [Column(TypeName = "decimal(37, 4)")]
        public decimal? Total { get; set; }
        public string ItemName { get; set; }
    }
}