// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwRoshetaOrders
    {
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public string Notes { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string OrderType { get; set; }
        [StringLength(200)]
        public string CustomerName { get; set; }
    }
}