// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwSalesInvoiceHeds
    {
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RealeDate { get; set; }
        [StringLength(200)]
        public string Safe { get; set; }
        [Required]
        [StringLength(200)]
        public string Deleviry { get; set; }
        [StringLength(200)]
        public string Customer { get; set; }
        [StringLength(450)]
        public int CustomerId { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? Shift { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Cash { get; set; }
        [Column(TypeName = "decimal(20, 2)")]
        public decimal? Later { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? invoiceTotal { get; set; }
        [StringLength(50)]
        public string InvoiceType { get; set; }
        public string Notes { get; set; }
        public int? SafeId { get; set; }
        public int? StoreId { get; set; }
    }
}