// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwStockWithdrawAndDeposit
    {
        public int Id { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [StringLength(200)]
        public string SafeName { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        public string Note { get; set; }
    }
}