// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwStoreInventory
    {
        public int StoreId { get; set; }
        [Required]
        [StringLength(10)]
        public string StoreName { get; set; }
        [StringLength(451)]
        public string ItemName { get; set; }
        public int ItemUnitId { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? Purchasess { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? SalesReturns { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? CommingFromStore { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? Saless { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? PurchaseReturns { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? GoingToStore { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? Qty { get; set; }
    }
}