// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechMain.DB_Models
{
    public partial class VwSuppliersTransactions
    {
        public int Id { get; set; }
        [StringLength(200)]
        public string SupplierName { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Qty { get; set; }
        [Required]
        [StringLength(200)]
        public string UserName { get; set; }
        [StringLength(200)]
        public string Safe { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string TransactionType { get; set; }
        public int? SheftId { get; set; }
        public int? SupplierId { get; set; }
    }
}