// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbCompanyInformation
    {
        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(200)]
        public string Phone { get; set; }
        [StringLength(200)]
        public string Address { get; set; }
        [StringLength(200)]
        public string WebSite { get; set; }
        [StringLength(200)]
        public string WorkField { get; set; }
        [StringLength(200)]
        public string TaxRecord { get; set; }
        [StringLength(200)]
        public string Mobile { get; set; }
        [StringLength(200)]
        public string Country { get; set; }
        [StringLength(200)]
        public string City { get; set; }
        [StringLength(200)]
        public string ImageName { get; set; }
        public string Note { get; set; }
        [Column(TypeName = "image")]
        public byte[] Pic { get; set; }
    }
}