// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbCustomers
    {
        public TbCustomers()
        {
            TbTransaction = new HashSet<TbTransaction>();
        }

        [Key]
        public string Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(200)]
        public string Phone { get; set; }
        public string Address { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? CreditLimit { get; set; }
        public string Note { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(450)]
        public string IdentityId { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }

        [InverseProperty("Cust")]
        public virtual ICollection<TbTransaction> TbTransaction { get; set; }
    }
}