// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbExpensesPayment
    {
        [Key]
        public int Id { get; set; }
        public int? ExpenseId { get; set; }
        public int? SafeId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Payment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public string Note { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? SheftId { get; set; }

        [ForeignKey(nameof(ExpenseId))]
        [InverseProperty(nameof(TbExpenses.TbExpensesPayment))]
        public virtual TbExpenses Expense { get; set; }
        [ForeignKey(nameof(SafeId))]
        [InverseProperty(nameof(TbSafes.TbExpensesPayment))]
        public virtual TbSafes Safe { get; set; }
        [ForeignKey(nameof(SheftId))]
        [InverseProperty(nameof(TbShifts.TbExpensesPayment))]
        public virtual TbShifts Sheft { get; set; }
    }
}