// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbItemUnits
    {
        public TbItemUnits()
        {
            TbPurchaseInvoiceItems = new HashSet<TbPurchaseInvoiceItems>();
            TbPurchaseReturnsDitails = new HashSet<TbPurchaseReturnsDitails>();
            TbSalesInvoiceItems = new HashSet<TbSalesInvoiceItems>();
            TbSalesReturnsDitails = new HashSet<TbSalesReturnsDitails>();
            TbStoreTransactionDetails = new HashSet<TbStoreTransactionDetails>();
        }

        [Key]
        public int Id { get; set; }
        public int? ItemId { get; set; }
        public int? UnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SalesPrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PuchasePrice { get; set; }
        [StringLength(200)]
        public string Barcode { get; set; }
        public int? UnitsNumber { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(ItemId))]
        [InverseProperty(nameof(TbItems.TbItemUnits))]
        public virtual TbItems Item { get; set; }
        [ForeignKey(nameof(UnitId))]
        [InverseProperty(nameof(TbUnits.TbItemUnits))]
        public virtual TbUnits Unit { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbPurchaseInvoiceItems> TbPurchaseInvoiceItems { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbPurchaseReturnsDitails> TbPurchaseReturnsDitails { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbSalesInvoiceItems> TbSalesInvoiceItems { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbSalesReturnsDitails> TbSalesReturnsDitails { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbStoreTransactionDetails> TbStoreTransactionDetails { get; set; }
    }
}