// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbPurchasesReturns
    {
        public TbPurchasesReturns()
        {
            TbPurchaseReturnsDitails = new HashSet<TbPurchaseReturnsDitails>();
        }

        [Key]
        public int Id { get; set; }
        public int? InvId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InvoiceDate { get; set; }
        public int? SafeId { get; set; }
        public int? SupplierId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? SheftId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Total { get; set; }
        public int? StoreId { get; set; }

        [ForeignKey(nameof(InvId))]
        [InverseProperty(nameof(TbPurchaseInvoices.TbPurchasesReturns))]
        public virtual TbPurchaseInvoices Inv { get; set; }
        [InverseProperty("Return")]
        public virtual ICollection<TbPurchaseReturnsDitails> TbPurchaseReturnsDitails { get; set; }
    }
}