// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbPurchaseInvoices
    {
        public TbPurchaseInvoices()
        {
            TbPurchaseInvoiceItems = new HashSet<TbPurchaseInvoiceItems>();
            TbPurchasesReturns = new HashSet<TbPurchasesReturns>();
        }

        [Key]
        public int Id { get; set; }
        public int? SafeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InvoiceDate { get; set; }
        public int SupplierId { get; set; }
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        public int SheftId { get; set; }
        public string Notes { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Total { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Cash { get; set; }
        public int? StoreId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RealDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CollectionDate { get; set; }
        [Column(TypeName = "decimal(19, 0)")]
        public decimal? Later { get; set; }

        [ForeignKey(nameof(SheftId))]
        [InverseProperty(nameof(TbShifts.TbPurchaseInvoices))]
        public virtual TbShifts Sheft { get; set; }
        [ForeignKey(nameof(StoreId))]
        [InverseProperty(nameof(TbStores.TbPurchaseInvoices))]
        public virtual TbStores Store { get; set; }
        [ForeignKey(nameof(SupplierId))]
        [InverseProperty(nameof(TbSuppliers.TbPurchaseInvoices))]
        public virtual TbSuppliers Supplier { get; set; }
        [InverseProperty("Invoice")]
        public virtual ICollection<TbPurchaseInvoiceItems> TbPurchaseInvoiceItems { get; set; }
        [InverseProperty("Inv")]
        public virtual ICollection<TbPurchasesReturns> TbPurchasesReturns { get; set; }
    }
}