// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbSalesReturns
    {
        public TbSalesReturns()
        {
            TbSalesReturnsDitails = new HashSet<TbSalesReturnsDitails>();
        }

        [Key]
        public int Id { get; set; }
        public int? InvId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InvoiceDate { get; set; }
        public int? SafeId { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? SheftId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Discount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Total { get; set; }
        [StringLength(50)]
        public string InvType { get; set; }
        public int? StoreId { get; set; }

        [ForeignKey(nameof(InvId))]
        [InverseProperty(nameof(TbSalesInvoices.TbSalesReturns))]
        public virtual TbSalesInvoices Inv { get; set; }
        [InverseProperty("Return")]
        public virtual ICollection<TbSalesReturnsDitails> TbSalesReturnsDitails { get; set; }
    }
}