// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbStoreTransactionDetails
    {
        [Key]
        public int Id { get; set; }
        public int? TransactionId { get; set; }
        public int? ItemUnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }

        [ForeignKey(nameof(ItemUnitId))]
        [InverseProperty(nameof(TbItemUnits.TbStoreTransactionDetails))]
        public virtual TbItemUnits ItemUnit { get; set; }
        [ForeignKey(nameof(TransactionId))]
        [InverseProperty(nameof(TbStoresTransaction.TbStoreTransactionDetails))]
        public virtual TbStoresTransaction Transaction { get; set; }
    }
}