// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class TbStockTransactions
    {
        [Key]
        public int Id { get; set; }
        public int? SafeFromId { get; set; }
        public int? SafeToId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public string Note { get; set; }

        [ForeignKey(nameof(SafeFromId))]
        [InverseProperty(nameof(TbSafes.TbStockTransactionsSafeFrom))]
        public virtual TbSafes SafeFrom { get; set; }
        [ForeignKey(nameof(SafeToId))]
        [InverseProperty(nameof(TbSafes.TbStockTransactionsSafeTo))]
        public virtual TbSafes SafeTo { get; set; }
    }
}