// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class VwCustomersBalance
    {
        public int? CustomerId { get; set; }
        [StringLength(200)]
        public string customerName { get; set; }
        [StringLength(200)]
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? CreditLimit { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? Debt { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? Credit { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? balance { get; set; }
        public int invCount { get; set; }
    }
}