// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class VwCustomersAccountStatement
    {
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InvoiceDate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Debt { get; set; }
        [Column(TypeName = "decimal(20, 2)")]
        public decimal? Credit { get; set; }
        [Column(TypeName = "numeric(3, 2)")]
        public decimal Balance { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        [StringLength(200)]
        public string customerName { get; set; }
        public int? CustomerId { get; set; }
        public bool? isInvoice { get; set; }
    }
}