// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class VwExpensesReport
    {
        public int ExpensesId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Payment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public string Note { get; set; }
        [StringLength(100)]
        public string ExpensesName { get; set; }
        [Required]
        [StringLength(200)]
        public string UserName { get; set; }
        public int? SheftId { get; set; }
        [StringLength(200)]
        public string SafeName { get; set; }
        public int? SafeId { get; set; }
    }
}