// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class VwItemsWithUnits
    {
        public int? ItemId { get; set; }
        public int? UnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SalesPrice { get; set; }
        [StringLength(451)]
        public string ItemName { get; set; }
        public int CategoryId { get; set; }
        [StringLength(200)]
        public string Barcode { get; set; }
        public int ItemUnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PuchasePrice { get; set; }
        public bool IsActive { get; set; }
        public int? UnitsNumber { get; set; }
    }
}