// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SaidalyTechBackEnd.DB_Models
{
    public partial class VwSafesBalance
    {
        public int Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? AllSales { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? AllCustomerPayment { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? AllPurchasesReturns { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? AllDeposit { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? OpeningBalances { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? AllCommingMony { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? AllPurchases { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? AllSalesReturns { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? AllExpenses { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? AllSupplierPayments { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? AllOutMony { get; set; }
        [Column(TypeName = "numeric(38, 2)")]
        public decimal? AllWithdrawal { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? AllMonyIn { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? AllMonyOut { get; set; }
        [Column(TypeName = "numeric(38, 0)")]
        public decimal? Balance { get; set; }
    }
}